### ISSUE TITLE
Export point cloud

### ISSUE THREAD

**Issue by HungNgoCT** [city-super/BungeeNeRF#13]
Hi.

Thank you for your useful code. Is there any ways to export point cloud, such as export to *.ply file?

Regards

**Comment by kam1107** [comment]
Hi, a possible way is to record all points and their weights during rendering. E.g. you can return all sampled points and weights in function render_rays using:  return ret, means, weights 

If you want to visualize pointed near the surface, just select the one with the highest density along the ray when saving the file.

**Comment by HungNgoCT** [comment]
Thank you kam1107. Will try.
