### ISSUE TITLE
Integrated Positional Encoding，where to use

### ISSUE THREAD

**Issue by zsz-pro** [city-super/BungeeNeRF#14]
![image](https://user-images.githubusercontent.com/61933660/187036781-c244c075-8216-4523-9679-f8559b257671.png)
Hi，it seems you did not use this function learned from MipNeRF, I only find its definition？Looking forward to your reply~

**Comment by kam1107** [comment]
IPE is integrated into the function: https://github.com/city-super/BungeeNeRF/blob/26cc7f4c848e20961dbf067114faa4268034349e/run_nerf_helpers.py#L76

**Comment by zsz-pro** [comment]
Thanks for your reply！
