### ISSUE TITLE
the last 2 dims of Poses information 

### ISSUE THREAD

**Issue by Yukun66** [city-super/BungeeNeRF#15]
Great work! I want to ask what the last 2 dimensions of the pose NumPy array mean. Because I notice there are 17 elements in the poses array and the last 2 elements are discarded. Like in the first pose the last two elements are 0.00358713 and 32.06129449. Thank you!

**Comment by kam1107** [comment]
In the original work the last two dims are near far bound. These two columns are not used: https://github.com/city-super/BungeeNeRF/blob/97a1c2587bc3e92d26736511d35ebb15eabbb7da/load_multiscale.py#L27
