### ISSUE TITLE
Something about the data

### ISSUE THREAD

**Issue by yueyisui** [city-super/BungeeNeRF#16]
First of all, I am grateful to the author for providing the source code. Then I want to run my own data with the BungeeNeRF. I have many UAV images, and I can use software such as colmap to calculate the image parameters and export the json file. But I find that the exported json file is different with yours. How can I convert it to the corresponding json file of the BungeeNeRF?

**Comment by kam1107** [comment]
Hi, if you use COLMAP to extract pose, please refer to the original NeRF work on LLFF dataset:https://github.com/bmild/nerf/blob/master/load_llff.py and this: https://github.com/Fyusion/LLFF/blob/c6e27b1ee59cb18f054ccb0f87a90214dbe70482/llff/poses/pose_utils.py#L11

**Comment by szgy66** [comment]
> First of all, I am grateful to the author for providing the source code. Then I want to run my own data with the BungeeNeRF. I have many UAV images, and I can use software such as colmap to calculate the image parameters and export the json file. But I find that the exported json file is different with yours. How can I convert it to the corresponding json file of the BungeeNeRF?

Do you have train the project on your own data? I had read his suggestion, but I still get the appropriate data type. Do you have any suggestions? Thanks!
