### ISSUE TITLE
Questions about using GES2pose.py

### ISSUE THREAD

**Issue by zhouxin191** [city-super/BungeeNeRF#21]
I have a question about generating trajectory pose files. I used the 56leonard.esp file you provided, imported it to Google Earth Studio, then exported the pose file 56leonard.json, and converted it using the script file GES2pose.py you provided, but the output pose is not the same as the poses_enu.json file provided directly in the dataset.
![Export 3D Tracking Data](https://user-images.githubusercontent.com/54947953/222969228-1d419fa6-fa78-495f-b4b7-698ad9aef031.png)
![Comparison](https://user-images.githubusercontent.com/54947953/222969486-85a5b1d8-86c6-400b-902a-43c0a3de8ce9.png)

**Comment by LongBN-L** [comment]
Hello, I have encountered the same problem as you mentioned. Have you resolved this issue？

**Comment by kam1107** [comment]
Hi, we additionally rotated the scene for 29 degree (https://en.wikipedia.org/wiki/Manhattanhenge#:~:text=In%20accordance%20with%20the%20Commissioners,the%20streets%20on%20that%20grid.) in the provided pose, but that's not necessary. You can still run the experiment using extracted poses.
