### ISSUE TITLE
Pretrained model available?

### ISSUE THREAD

**Issue by evelinehong** [city-super/BungeeNeRF#3]
Hi,
Do you have pretrained model / checkpoint?
Also, what 's the training time for a scene?

Thanks

**Comment by kam1107** [comment]
Hi, the training time depends on how you partition the scales. For example, on 56Leonard scene, we use a 4-stage training. The training time on a single A100 card is approx 2.5~3hr for stage0 and 1(until convergence); for stage2 and 3, it can take 12~15hr to train. Checkpoints will be released soon.

**Comment by bityangke** [comment]
i train on a single A100 card with the default setting， it took 11.5 hours to train stage0 on 56Leonard.

**Comment by kam1107** [comment]
30w iters is more than enough for stage0 to converge. You can stop stage training early when the curve tends to converge (or already converges).

**Comment by Wei-Baldwin-Zeng** [comment]
Hi，great work!!!!!!

Is there any tricks that I should pay attention to when training the model? It took me almost~ 4 days to train, but the results didn't reach what showed in the paper, but almost like the ones for the original NeRF showed in your paper (blur around the boundary and lost details). 

For example, is the cofigs keep the same for the 4 stages? Any other parameters need to change for different stages?

Really appreciate your reply.

**Comment by kam1107** [comment]
What's the PSNR you got for each stage? You may try to increase learning rate to see if it helps. Also remember to load checkpoint from previous training stage when switching to a new scale.

**Comment by Wei-Baldwin-Zeng** [comment]
Thank you for your quick reply. Yes, I've make sure to load the checkpoint from the previous training stage. 

For each stage, the PSNR was around 22.5~22.7 (56leonard), and the render_test results, visually somehow look like the original NeRF in the Figure 5 in your paper, blurry artifacts at edges. 

I haven't change anything in the config for each stage, just copy to 4 configs for 4 training stages. So I wonder if there is anything I actually need to change when switching to a new scale. 

Now I'm trying to train each stage longer to see if there is any difference. Also looking forward to your pretrained model so I can direct see the results. 

Best regards,

**Comment by kam1107** [comment]
I think there's a mistake in render_path function. I manually assigned the stage variable to 0 in function render(..). Can you try to replace it with e.g. stage=3 to see if you can get better results? I will correct this later.

**Comment by Wei-Baldwin-Zeng** [comment]
Hi,

I have corrected the mistake you mentioned in render_path, still, the rendering results looks not as good as in the paper. 

In total, using a V100, I trained around 1week, 4 stages, for each stage, the PSNR is around 23.2. But the rendering results still has the same blurry artifacts at edges.

**Comment by kam1107** [comment]
Can you show some examples? My retrain results look fine 🤔

**Comment by yangqingqing007** [comment]
> Can you show some examples? My retrain results look fine 🤔

Is the result in your paper trained with original image or downsampling? (is factor 3 or other value used?) .  3Q~

**Comment by kam1107** [comment]
> > Can you show some examples? My retrain results look fine thinking
> 
> Is the result in your paper trained with original image or downsampling? (is factor 3 or other value used?) . 3Q~

Those are trained on downsampled images as specified in the config files

**Comment by kam1107** [comment]
Pretrained models of 56leonard and Transamerica have been uploaded to the data drive: https://drive.google.com/drive/folders/1W4iEUyTe6YaNVS0ou9DRgmYV5zSAXDIn?usp=sharing. Take a look if you are interested :)

**Comment by wzpscott** [comment]
> Pretrained models of 56leonard and Transamerica have been uploaded to the data drive: https://drive.google.com/drive/folders/1W4iEUyTe6YaNVS0ou9DRgmYV5zSAXDIn?usp=sharing. Take a look if you are interested :)

It seems that the checkpoints are corrupted. Loading the checkpoints gives a '_pickle.UnpicklingError: A load persistent id instruction was encountered, but no persistent_load function was specified.' error.
