### ISSUE TITLE
How to run this code on the custom data?

### ISSUE THREAD

**Issue by DapengFeng** [city-super/BungeeNeRF#4]

**Comment by kam1107** [comment]
If you already have images and poses, you need to partition your data to different scale and record where you split it. E.g. in our Google earth datasets, the camera gradually moves far away. So in pose_enu.json, the entry "scale_split": [325, 195, 65, 0] means: stage0(furthest scale) ranges from image index 325 until the end; stage1(a closer scale) ranges from image index 195 until 325 etc.

**Comment by bycloudai** [comment]
Hi @kam1107 
what did you guys used to estimate the poses?
thank you
