### ISSUE TITLE
Why does it have poor quality for my train and render

### ISSUE THREAD

**Issue by hzhshok** [city-super/BungeeNeRF#6]
Hello, thanks for you sharing the fantastic work.
 Now i download the example data and following the demo, but the the output 11 png images are not as the paper show, i don't know if  my configuration parameter are not optimizated?  the following is my configuration, 

Could you help give me a suggestion? 

Event the render quality is lower than the original images.

Hardware: GPU: 3080(24G)

Configuration: using default - 200000 iteraters.

Regards
![011](https://user-images.githubusercontent.com/52768640/182088188-2e71f5c3-4cf4-446b-b48f-25ab12e236cd.png)

Total 11 images.

**Comment by hzhshok** [comment]
@kam1107 Thanks lots for your quick response！

i will try that to get more level detailed renders.

**Comment by Wei-Baldwin-Zeng** [comment]
Do your render results getting better?

My render results look like yours, blurry around edges and loss details.

**Comment by hzhshok** [comment]
Yes, it is better on my second step, and i just run two steps because the speed is very too slow and cost more machine performance.

**Comment by atztao** [comment]
@hzhshok Hey, how long is the runtime ?
