### ISSUE TITLE
How to easily generate the rendering trajactories when evaluation?

### ISSUE THREAD

**Issue by Wei-Baldwin-Zeng** [city-super/BungeeNeRF#7]
Hi, Amazing work!!!!!

How can I generate the rendering trajactories when I'm trying to evaluate the trained model? I couldn't find an easy way to do that. 

Looking forward to your reply.

**Comment by kam1107** [comment]
To evaluate the model trained on the provided dataset, you should use the test set. If you are trying to render a new trajectory, the easiest way is to create one in Google Earth Studio and use the generated cam poses.

**Comment by Wei-Baldwin-Zeng** [comment]
Thank you for your reply. 

Yes, using the test set to evaluate the trained model, which I can understand, because you need the gt to calculate the PSNR, right? 

When I have finished training, if I just want to play around the trained model, is there any way to create a new rendering trajectory for me to render new views (or even just create some new rendering view points it's ok) , besides using Google Earth Studio to create one?

**Comment by kam1107** [comment]
In our setting, we transformed the coordinate system into ENU (https://en.wikipedia.org/wiki/Local_tangent_plane_coordinates) with the origin set to the center building. If you don't want to use GES you can also mathematically calculate a curve.
