### ISSUE TITLE
How to convert data from GES export

### ISSUE THREAD

**Issue by FlushingCat** [city-super/BungeeNeRF#8]
Greetings!

I have experimented and reproduced according to the instructions with great results. 

But I ran into some problems when using a custom dataset. How should the 3D Camera data extracted from Google Earth Studio be converted into the format used for model training?

I tried to simply pass "rotation" through x'=-x, y'=180-y, z'=180+z to get Euler angles, then convert it to a rotation matrix, and finally combine it with the "position" (after scaling down), but this will cause errors during training and will not get the pose representation in the example dataset

Could you please describe in detail how to convert the data exported from GES?

**Comment by kam1107** [comment]
Hi, I newly added a sample script of how we generally convert GES camera data to poses: https://github.com/city-super/BungeeNeRF/blob/main/GES2pose.py

**Comment by lczlczlcz** [comment]
GES2pose.py cannot be opened at present. Can you upload another copy？

**Comment by lf-191** [comment]
How you implemented using a custom dataset
