### ISSUE TITLE
Rendering the results

### ISSUE THREAD

**Issue by bycloudai** [city-super/BungeeNeRF#9]
Hi, thank you for sharing the codes of your amazing research!

Just curious, right now I am using the default render `poses_enu.json` file, and it only produces 29 frames. 
How can I generate one from a custom `.esp` from Google Earth and convert that into `poses_enu.json` file?
I understand you wrote a description about how to convert it and such, but I think I am failing to replicate that. 
Any help would be appreciated!

**Comment by kam1107** [comment]
Hi, I newly added a sample script of how we generally convert GES camera data to poses: https://github.com/city-super/BungeeNeRF/blob/main/GES2pose.py

**Comment by bycloudai** [comment]
Hi thank you so much for your response, the script works perfectly!
However, it doesn't seem to be able to adjust to make it output more than 29 frames, do you mind sharing how I can control that? Thank you.

**Comment by bycloudai** [comment]
nvm I figured it out. 
After specifying the argument `--holdout 1` it worked. 
Thank you
